workspace:
  base: /code
  path: ""

steps:
  build:
    image: quay.kawa.tf/tqdv/smapi-mod:3.18.4
    commands:
      - cp TinkersValley/TinkersValley-woodpecker.csproj.local TinkersValley/TinkersValley.csproj.local
      - dotnet build -c Release
    when:
      - event: tag
      - event: manual
      - event: push
        branch: ci-*

  prepare-artifacts:
    image: busybox
    commands:
      # Rename the artifact file from "TinkersValley 2.2.9.zip" to "TinkersValley-v2.2.9.zip"
      # Notably because GitHub automatically converts spaces to dots, so the file ends up
      # being named "TinkersValley.2.2.9.zip" which looks confusing
      - cp TinkersValley/bin/Release/*/TinkersValley*.zip "TinkersValley-v${CI_COMMIT_TAG}.zip"
    when:
      - event: tag

  publish:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: TinkersValley-*.zip
      title: ${CI_COMMIT_TAG}
      note: _Automatically created by the Woodpecker pipeline_
      prerelease: true
    when:
      - event: tag